### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by gnanadeeptu** [joeferraro/MavensMate-Desktop#82]
Request for Help!!!
I was on version 6 and upgraded to 9. I am getting a JavaScript error with the following message. Also attached the screen shot of the same.
![screen shot 2015-10-08 at 3 42 05 pm](https://cloud.githubusercontent.com/assets/1222452/10381928/962e1cec-6dd3-11e5-902a-e85073c98b36.png)

Uncaught Exception:
Error: Error parsing your JSON configuration file: [/Users/Giene/.mavensmate-config.json].
    at File.loadSync (/Applications/MavensMate.app/Contents/Resources/app/node_modules/nconf/lib/nconf/stores/file.js:141:13)
    at Provider.add (/Applications/MavensMate.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:135:23)
    at Provider.file (/Applications/MavensMate.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:61:15)
    at Client._initConfig (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:267:10)
    at Client.reloadConfig (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:237:8)
    at StatWatcher.<anonymous> (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:293:10)
    at emitTwo (events.js:87:13)
    at StatWatcher.emit (events.js:172:7)
    at StatWatcher._handle.onchange (fs.js:1295:10)

**Comment by joeferraro** [comment]
I'll have a look but my recommendation would be to delete `.mavensmate-config.json` from your `~/` directory as it's having trouble parsing it for some reason

**Comment by gnanadeeptu** [comment]
Hi Joe, I don't see that file at all. 
![screen shot 2015-10-08 at 4 00 18 pm](https://cloud.githubusercontent.com/assets/1222452/10382148/e1482a40-6dd5-11e5-8b0b-1d507a661467.png)

**Comment by gnanadeeptu** [comment]
On a side note, thought this might help.
I have checked "Download categorized Apex unit test logs (mm_download_categorized_test_logs)" option and boom the error pop'ed up.

**Comment by joeferraro** [comment]
Hi @gnanadeeptu that's your project's config directory. In your home directory (`~/`), there should be a file called `.mavensmate-config.json`. Can you post the contents of that file?

**Comment by gnanadeeptu** [comment]
Hi Joe,

I have delete the .json file, also to save some of my time run-time I have re-did everything from scratch. Deleted all the existing workspace folders and created a brand new project again.

**Comment by gnanadeeptu** [comment]
Thanks @joeferraro for taking time and closing this ticket after an year.
