### ISSUE TITLE
Receiving EPERM error when trying to clean, referesh metadata, or flush logs if Atom.io is open

### ISSUE THREAD

**Issue by banderson5144** [joeferraro/MavensMate-Desktop#85]
Subject is a little long but describes it perfectly

**Comment by joeferraro** [comment]
Hi, can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate-app/blob/master/CONTRIBUTING.md

**Comment by banderson5144** [comment]
2015-10-09T12:59:16.709Z - info: initiated client:  {"name":"mavensmate-app","isServer":true,"isNodeApp":false,"isCommandLine":false,"settings":{"type":"literal"}}
2015-10-09T12:59:18.042Z - debug: Processing request GET for URL: /app/home/index
2015-10-09T12:59:18.119Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap.css
2015-10-09T12:59:18.122Z - silly: Processing request GET for URL: /app/static/css/flat-ui.css
2015-10-09T12:59:18.123Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap-responsive.css
2015-10-09T12:59:18.129Z - silly: Processing request GET for URL: /app/static/css/mavensmate.css
2015-10-09T12:59:18.130Z - silly: Processing request GET for URL: /app/static/css/dynatree.css
2015-10-09T12:59:18.131Z - silly: Processing request GET for URL: /app/static/css/font-awesome.min.css
2015-10-09T12:59:18.133Z - silly: Processing request GET for URL: /app/static/css/prettify.css
2015-10-09T12:59:18.135Z - silly: Processing request GET for URL: /app/static/js/jquery.js
2015-10-09T12:59:18.137Z - silly: Processing request GET for URL: /app/static/js/jqueryui.js
2015-10-09T12:59:18.138Z - silly: Processing request GET for URL: /app/static/js/bootstrap.min.js
2015-10-09T12:59:18.139Z - silly: Processing request GET for URL: /app/static/js/bootstrap-select.js
2015-10-09T12:59:18.143Z - silly: Processing request GET for URL: /app/static/js/flatui-checkbox.js
2015-10-09T12:59:18.144Z - silly: Processing request GET for URL: /app/static/js/mavensmate.js
2015-10-09T12:59:18.148Z - silly: Processing request GET for URL: /app/static/js/dynatree2.js
2015-10-09T12:59:18.149Z - silly: Processing request GET for URL: /app/static/js/jquery.contextMenu-custom.js
2015-10-09T12:59:18.149Z - silly: Processing request GET for URL: /app/static/js/prettify.js
2015-10-09T12:59:18.153Z - silly: Processing request GET for URL: /app/static/images/burger.png
2015-10-09T12:59:18.156Z - silly: Processing request GET for URL: /app/static/images/open-project.png
2015-10-09T12:59:18.157Z - silly: Processing request GET for URL: /app/static/images/logo2.png
2015-10-09T12:59:22.394Z - silly: Processing request GET for URL: /app/static/fonts/Flat-UI-Icons.woff
2015-10-09T12:59:25.473Z - debug: Processing request GET for URL: /app/home/index?pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T12:59:25.473Z - debug: query params pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T12:59:25.474Z - debug: _findProjectPathById
2015-10-09T12:59:25.474Z - debug: 9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T12:59:25.474Z - debug:  0=C:\atom_sf_proj
2015-10-09T12:59:25.475Z - debug: C:\atom_sf_proj
2015-10-09T12:59:25.475Z - debug:  0=C:\atom_sf_proj\CAPREIT_QA, 1=C:\atom_sf_proj\ERIC_ANALYTICS, 2=C:\atom_sf_proj\FAEF_CC, 3=C:\atom_sf_proj\GA_UAT
2015-10-09T12:59:25.476Z - info: adding project by id ---->  9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T12:59:25.476Z - info: path:  C:\atom_sf_proj\CAPREIT_QA
2015-10-09T12:59:25.476Z - debug: initing existing project ...
2015-10-09T12:59:25.477Z - debug: project name CAPREIT_QA
2015-10-09T12:59:25.477Z - debug: project path C:\atom_sf_proj\CAPREIT_QA
2015-10-09T12:59:25.478Z - debug: initing package instance
2015-10-09T12:59:25.478Z - debug: deserializing: C:\atom_sf_proj\CAPREIT_QA\src\package.xml
2015-10-09T12:59:25.481Z - error: Could not initiate existing Project instance: Could not initiate Package instance by path: ENOENT: no such file or directory, open 'C:\atom_sf_proj\CAPREIT_QA\src\package.xml'
2015-10-09T12:59:25.483Z - error: Error initializing project: Could not initiate Package instance by path: ENOENT: no such file or directory, open 'C:\atom_sf_proj\CAPREIT_QA\src\package.xml' -> Error: Could not initiate Package instance by path: ENOENT: no such file or directory, open 'C:\atom_sf_proj\CAPREIT_QA\src\package.xml'
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\package.js:81:20
    at tryCatch1 (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
    at Promise._callHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
    at Promise._settlePromiseFromHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAt (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
    at Promise._settlePromises (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:845:14)
    at Async._consumeFunctionBuffer (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
    at Async.consumeFunctionBuffer (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
2015-10-09T13:00:04.790Z - debug: Processing request GET for URL: /app/home/index?pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:04.790Z - debug: query params pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:04.790Z - debug: _findProjectPathById
2015-10-09T13:00:04.791Z - debug: 9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:04.791Z - debug:  0=C:\atom_sf_proj
2015-10-09T13:00:04.791Z - debug: C:\atom_sf_proj
2015-10-09T13:00:04.792Z - debug:  0=C:\atom_sf_proj\CAPREIT_QA, 1=C:\atom_sf_proj\ERIC_ANALYTICS, 2=C:\atom_sf_proj\FAEF_CC, 3=C:\atom_sf_proj\GA_UAT
2015-10-09T13:00:04.794Z - info: adding project by id ---->  9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:04.794Z - info: path:  C:\atom_sf_proj\CAPREIT_QA
2015-10-09T13:00:04.794Z - debug: initing existing project ...
2015-10-09T13:00:04.795Z - debug: project name CAPREIT_QA
2015-10-09T13:00:04.795Z - debug: project path C:\atom_sf_proj\CAPREIT_QA
2015-10-09T13:00:04.796Z - debug: initing package instance
2015-10-09T13:00:04.796Z - debug: deserializing: C:\atom_sf_proj\CAPREIT_QA\src\package.xml
2015-10-09T13:00:04.819Z - debug: parsed package.xml to -->{"ApexClass":"*","ApexPage":"*","ApexTrigger":"*","StaticResource":"*"}
2015-10-09T13:00:04.821Z - debug: setting package subscription: 
2015-10-09T13:00:04.821Z - debug:  ApexClass=*, ApexPage=*, ApexTrigger=*, StaticResource=*
2015-10-09T13:00:04.827Z - debug: initiating SalesforceClient: 
2015-10-09T13:00:04.829Z - debug: initializing connection to salesforce ...
2015-10-09T13:00:04.830Z - debug: logging in to salesforce: https://test.salesforce.com/
2015-10-09T13:00:05.172Z - debug: getting user information:
2015-10-09T13:00:05.295Z - debug: logged in successfully
2015-10-09T13:00:05.295Z - debug: configuring jsforce ...
2015-10-09T13:00:05.587Z - debug: writing local session
2015-10-09T13:00:05.587Z - silly:  accessToken=00D550000005Gj2!AQ4AQMZAECYwTpRIeazZkSyUz4U6sLiewIHq8QFR5nuFK.kvd3BGXRxfjwMDKO17LN8u1E0EJZRP1oCIGcpQceDJdFm8rCCM, instanceUrl=https://cs41.salesforce.com
2015-10-09T13:00:05.601Z - silly: getting metadata type by name: ApexClass
2015-10-09T13:00:05.601Z - silly:  directoryName=classes, inFolder=false, metaFile=true, suffix=cls, xmlName=ApexClass
2015-10-09T13:00:05.601Z - silly: getting metadata type by name: ApexPage
2015-10-09T13:00:05.601Z - silly:  directoryName=pages, inFolder=false, metaFile=true, suffix=page, xmlName=ApexPage
2015-10-09T13:00:05.601Z - silly: getting metadata type by name: ApexTrigger
2015-10-09T13:00:05.601Z - silly:  directoryName=triggers, inFolder=false, metaFile=true, suffix=trigger, xmlName=ApexTrigger
2015-10-09T13:00:05.602Z - silly: getting metadata type by name: StaticResource
2015-10-09T13:00:05.602Z - silly:  directoryName=staticresources, inFolder=false, metaFile=true, suffix=resource, xmlName=StaticResource
2015-10-09T13:00:05.851Z - debug: starting system streaming listener
2015-10-09T13:00:05.868Z - debug: streaming listener successfully configured
2015-10-09T13:00:05.897Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap.css
2015-10-09T13:00:05.901Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap-responsive.css
2015-10-09T13:00:05.902Z - silly: Processing request GET for URL: /app/static/css/flat-ui.css
2015-10-09T13:00:05.903Z - silly: Processing request GET for URL: /app/static/css/mavensmate.css
2015-10-09T13:00:05.904Z - silly: Processing request GET for URL: /app/static/css/dynatree.css
2015-10-09T13:00:05.904Z - silly: Processing request GET for URL: /app/static/css/font-awesome.min.css
2015-10-09T13:00:05.906Z - silly: Processing request GET for URL: /app/static/css/prettify.css
2015-10-09T13:00:05.910Z - silly: Processing request GET for URL: /app/static/js/jquery.js
2015-10-09T13:00:05.912Z - silly: Processing request GET for URL: /app/static/js/jqueryui.js
2015-10-09T13:00:05.913Z - silly: Processing request GET for URL: /app/static/js/bootstrap.min.js
2015-10-09T13:00:05.914Z - silly: Processing request GET for URL: /app/static/js/bootstrap-select.js
2015-10-09T13:00:05.915Z - silly: Processing request GET for URL: /app/static/js/flatui-checkbox.js
2015-10-09T13:00:05.916Z - silly: Processing request GET for URL: /app/static/js/mavensmate.js
2015-10-09T13:00:05.921Z - silly: Processing request GET for URL: /app/static/js/dynatree2.js
2015-10-09T13:00:05.926Z - silly: Processing request GET for URL: /app/static/js/jquery.contextMenu-custom.js
2015-10-09T13:00:05.931Z - silly: Processing request GET for URL: /app/static/js/prettify.js
2015-10-09T13:00:05.932Z - silly: Processing request GET for URL: /app/static/images/burger.png
2015-10-09T13:00:05.940Z - silly: Processing request GET for URL: /app/static/images/open-project.png
2015-10-09T13:00:05.942Z - silly: Processing request GET for URL: /app/static/images/logo2.png
2015-10-09T13:00:15.005Z - debug: Processing request GET for URL: /app/project/edit?pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:15.006Z - debug: query params pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:15.101Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap.css
2015-10-09T13:00:15.102Z - silly: Processing request GET for URL: /app/static/bootstrap/css/bootstrap-responsive.css
2015-10-09T13:00:15.103Z - silly: Processing request GET for URL: /app/static/css/flat-ui.css
2015-10-09T13:00:15.103Z - silly: Processing request GET for URL: /app/static/css/mavensmate.css
2015-10-09T13:00:15.104Z - silly: Processing request GET for URL: /app/static/css/dynatree.css
2015-10-09T13:00:15.105Z - silly: Processing request GET for URL: /app/static/css/font-awesome.min.css
2015-10-09T13:00:15.107Z - silly: Processing request GET for URL: /app/static/css/prettify.css
2015-10-09T13:00:15.108Z - silly: Processing request GET for URL: /app/static/js/jquery.js
2015-10-09T13:00:15.109Z - silly: Processing request GET for URL: /app/static/js/jqueryui.js
2015-10-09T13:00:15.110Z - silly: Processing request GET for URL: /app/static/js/bootstrap.min.js
2015-10-09T13:00:15.111Z - silly: Processing request GET for URL: /app/static/js/bootstrap-select.js
2015-10-09T13:00:15.112Z - silly: Processing request GET for URL: /app/static/js/flatui-checkbox.js
2015-10-09T13:00:15.115Z - silly: Processing request GET for URL: /app/static/js/mavensmate.js
2015-10-09T13:00:15.116Z - silly: Processing request GET for URL: /app/static/js/dynatree2.js
2015-10-09T13:00:15.116Z - silly: Processing request GET for URL: /app/static/js/jquery.contextMenu-custom.js
2015-10-09T13:00:15.117Z - silly: Processing request GET for URL: /app/static/js/prettify.js
2015-10-09T13:00:15.119Z - silly: Processing request GET for URL: /app/static/images/burger.png
2015-10-09T13:00:15.121Z - silly: Processing request GET for URL: /app/static/images/open-project.png
2015-10-09T13:00:15.122Z - silly: Processing request GET for URL: /app/static/images/logo2.png
2015-10-09T13:00:15.300Z - silly: Processing request GET for URL: /app/static/font/fontawesome-webfont.woff?v=3.1.0
2015-10-09T13:00:15.301Z - debug: query params v=3.1.0
2015-10-09T13:00:15.439Z - debug: Processing request POST for URL: /app/project/get-index?pid=9e7ec950-685b-11e5-9d28-bdbff12d48ea
2015-10-09T13:00:15.439Z - debug: post body packageLocation=null
2015-10-09T13:00:15.440Z - info: 

==================> executing command: get-metadata-index

2015-10-09T13:00:15.440Z - info: executeCommandForProject payload is: {"packageLocation":null}
2015-10-09T13:00:15.440Z - debug: command class is: GetMetadataIndexCommand
2015-10-09T13:00:15.442Z - silly: Processing request GET for URL: /app/static/images/loading.gif
2015-10-09T13:00:15.451Z - silly: getting metadata type by name: ApexClass
2015-10-09T13:00:15.451Z - silly:  directoryName=classes, inFolder=false, metaFile=true, suffix=cls, xmlName=ApexClass
2015-10-09T13:00:15.452Z - silly: getting metadata type by name: ApexPage
2015-10-09T13:00:15.452Z - silly:  directoryName=pages, inFolder=false, metaFile=true, suffix=page, xmlName=ApexPage
2015-10-09T13:00:15.452Z - silly: getting metadata type by name: ApexTrigger
2015-10-09T13:00:15.452Z - silly:  directoryName=triggers, inFolder=false, metaFile=true, suffix=trigger, xmlName=ApexTrigger
2015-10-09T13:00:15.452Z - silly: getting metadata type by name: StaticResource
2015-10-09T13:00:15.452Z - silly:  directoryName=staticresources, inFolder=false, metaFile=true, suffix=resource, xmlName=StaticResource
2015-10-09T13:00:15.456Z - info: Looking for finish command(s) for get-metadata-index
2015-10-09T13:00:15.456Z - info: handling command result: 
2015-10-09T13:00:15.456Z - debug:  

==================> executing command: edit-project

2015-10-09T13:00:17.542Z - info: executeCommandForProject payload is: {"package":{"ApexClass":"*","ApexPage":"*","ApexTrigger":"*","StaticResource":"*"},"path":"C:atom_sf_projCAPREIT_QA","command":"edit-project"}
2015-10-09T13:00:17.542Z - debug: command class is: EditProjectCommand
2015-10-09T13:00:17.543Z - debug: editing project, requested package is:  ApexClass=*, ApexPage=*, ApexTrigger=*, StaticResource=*
2015-10-09T13:00:17.543Z - debug: retrieving unpackaged: 
2015-10-09T13:00:17.543Z - debug:  ApexClass=*, ApexPage=*, ApexTrigger=*, StaticResource=*
2015-10-09T13:00:17.552Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:17.552Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:20.561Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:20.561Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:21.879Z - debug: writing stream
2015-10-09T13:00:21.914Z - debug: closed write stream, unzipping now
2015-10-09T13:00:21.928Z - debug: cscriptExe is:  cscript
2015-10-09T13:00:23.566Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:23.566Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:26.570Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:26.570Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:29.573Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:29.574Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:32.580Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:32.580Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:35.583Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:35.583Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:38.587Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:38.587Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:41.593Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:41.593Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:44.599Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:44.599Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:47.602Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:47.602Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:47.802Z - info: handling command result: 
2015-10-09T13:00:47.802Z - error:  Error: EPERM: operation not permitted, unlink 'C:\atom_sf_proj\CAPREIT_QA\src\classes'
    at Error (native)
2015-10-09T13:00:47.802Z - debug: finishing jobid: b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:47.802Z - error:  Error: EPERM: operation not permitted, unlink 'C:\atom_sf_proj\CAPREIT_QA\src\classes'
    at Error (native)
2015-10-09T13:00:50.607Z - debug: Processing request GET for URL: /status?id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:50.607Z - debug: query params id=b07dac40-6e85-11e5-812a-bffd2076cb13
2015-10-09T13:00:50.613Z - silly: Processing request GET for URL: /app/static/fonts/Flat-UI-Icons.woff
2015-10-09T13:00:50.623Z - silly: Processing request GET for URL: /app/static/sounds/ding.mp3

**Comment by banderson5144** [comment]
Windows 8.1 64 Bit
MavensMate 0.0.9
Hit update project button in MM when any metadata file is open in Atom.io

**Comment by joeferraro** [comment]
@banderson5144 There are some super pesky PERM-related issues with node on windows. this update changes the way we do cleans/refreshes/edits of the src directory. let me know if it works for you: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta4
